language: generic

sudo: required

services:
  - docker

script:
  - docker build -t cv -f Dockerfile .
  - docker run --rm -v $(pwd)/output:/tmp cv:latest sh -c "cp -r cv.pdf cv.ps cv.html cv.dvi /tmp/"
  - ls -ltr $(pwd)/output/

deploy:
  provider: releases
  api_key:
    secure: "q2tS+NiXQBzTj9HczgewmtHnoLY8mnJWwYRsMOUduqKTDNiQZRe79sBlWKf9n5wt3PBf7odOEIDq+yUOFghechAmXbRsPUbPIqd7BDDPbARIFgk4jj2BhMYAxpAEYrQjjIl7weuw4AX4ujn0EorEfOI2g1Vxg/hK+cF7jcEZX+4djo3KQpWw2fQnV0bVbRHextv5m+G3FJ/vUIeuwwb2RkqBG5L1VIvjuq5zVZbCuCxWJoxDP41+HJGNS0DszHkUz4f5/+NukX7qn3vGSRPaPA5zOcM237ud9ZUNHdSU5w2atKE/9G6Lo12z29D5KDl1jbzPOIVsC4oCQwB0uCzR+/3C5Ipr0V4Dl0ga8AxC++PceQkjYSygMU9SB31o1UnsbpdDUsjkUggCjtw2Y/EKH2vDsys/aJXqGn/6vd2g2LQUGP18d69m95V9zyXwmNf183zbxwBCM6RWTPRCyoWoe82aik55W3MwY/3PGiMjwiabBqWV8WruI0NxCtuh217tT8O5mwBzlKWWHQQeeTSHIv2xP1tCi3GnypiJJq03p06VPo3sO7SZZSEpydJLuMymlM8LLDj9TOlwD2Eab0zjMWHkpIe/e1INoR0+6ewgNolgrd7LcaoxocVP79zGx6nFthNWD5llvtJgFfV97KDGV8qEjo3tC8vQXz7M0bwEPK8="
  file: "output/cv.pdf"
  on:
    repo: kylegordon/cv
    branch: master
